# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

books = Book.create!([{title: 'Therese Raquin', author: 'Emile Zola', quote: 'She thought of her lover as being like a dog that would guard and protect her. Her cool, calm skin felt no shudder of desire.', isbn: '0140449442'}, {title: 'Purity', author: 'Jonathan Franzen', quote: "There's the imperative to keep secrets, and the imperative to have them known. How do you know that you're a person, distinct from other people? By keeping certain things to yourself. You guard them inside you, because, if you don't, there's no distinction between inside and outside. Secrets are the way you know you even have an inside... But identity inside a vacuum is also meaningless. Sooner or later, the inside of you needs a witness. Otherwise, you're just a cow, a cat, a stone, a thing in the world, trapped in your thingness.", isbn: '0007532768'}, {title: 'Jonathan Strange and Mr Norrell', author: 'Susanna Clarke', quote: 'Upon my word, there is nothing in the world so easy to explain as failure - it is, after all, what everybody does all the time.', isbn: '1408856883'}, {title: "The Teleportation Accident", author: "Ned Beauman", quote: "Anything they did there would be so much better than anything they could do in America, which was nothing now but a dry goods company pretending to be a nation", isbn: "034099844X"}, {title: "The Pregnant Widow", author: "Martin Amis", quote: "His wound, when it came - it didn't hurt a bit. It was the sensory opposite of torture. She loomed up on him unclothed and unarmed, with her pincers of bliss - her lips, her fingertips... It was the opposite of torture, yet it twisted. It ruined him for twenty-five years", isbn: "0224076124"}, {title: "Nausea", author: "Jean-Paul Sartre", quote: "I'm going to bed. I'm cured. I'll give up writing my daily impressions like a little girl in her nice new notebook", isbn: "014118549X"} ])
